services:
  textreport:
    image: ghcr.io/therepos/textreport:latest
    container_name: textreport
    ports:
      - "3021:8090"
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined
    pull_policy: always